### ISSUE TITLE
Cannot compile games-action/multimc5-999, CMake cannot find Qt5TestConfig.cmake

### ISSUE THREAD

**Issue by UntouchedWagons** [TheCrueltySage/vampire-overlay#1]
Hey there, I'm trying to compile MultiMC but it fails, for some reason CMake is looking for a package with the name of Qt5TestConfig.cmake or qt5test-config.cmake but cannot find it. I'll try and post the build log in a moment.

[build.txt](https://github.com/TheCrueltySage/vampire-overlay/files/2024063/build.txt)

**Comment by TheCrueltySage** [comment]
Sorry about not answering for so long, apparently I forgot to actually make github email me with my issues.
Not sure if you still care, but the problem was in missing qttest dependency in ebuild.
Should be fixed now. Feel free to reopen the issue if you still have problems.
