### ISSUE TITLE
citra-9999.ebuild won't build with clang because of -fno-new-ttp-matching

### ISSUE THREAD

**Issue by madsl** [TheCrueltySage/vampire-overlay#8]
It's been like this for a very long time, but thought I should mention it:

append-cxxflags "-fno-new-ttp-matching"

This flag makes the configure step fail if you build with clang, clang++ does not support that cxxflag. Why is it there...?

**Comment by TheCrueltySage** [comment]
Deleted the line.
It still doesn't build for me right, to be honest, but at least not because of this line.
