### ISSUE TITLE
Citra-9999 fails to build

### ISSUE THREAD

**Issue by RefinedAnarchy** [TheCrueltySage/vampire-overlay#9]
-- Check for working CXX compiler: /usr/lib/llvm/10/bin/clang++ -- broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/lib/llvm/10/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /var/tmp/portage/games-emulation/citra-9999/work/citra-9999_build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake cmTC_43dff/fast && /usr/bin/gmake -f CMakeFiles/cmTC_43dff.dir/build.make CMakeFiles/cmTC_43dff.dir/build
    gmake[1]: Entering directory '/var/tmp/portage/games-emulation/citra-9999/work/citra-9999_build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_43dff.dir/testCXXCompiler.cxx.o
    /usr/lib/llvm/10/bin/clang++    -DNDEBUG -march=znver1 -O2 -pipe -stdlib=libc++ -fno-new-ttp-matching    -o CMakeFiles/cmTC_43dff.dir/testCXXCompiler.cxx.o -c /var/tmp/portage/games-emulation/citra-9999/work/citra-9999_build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang-10: error: unknown argument: '-fno-new-ttp-matching'
    gmake[1]: *** [CMakeFiles/cmTC_43dff.dir/build.make:66: CMakeFiles/cmTC_43dff.dir/testCXXCompiler.cxx.o] Error 1
    gmake[1]: Leaving directory '/var/tmp/portage/games-emulation/citra-9999/work/citra-9999_build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:121: cmTC_43dff/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)

**Comment by TheCrueltySage** [comment]
I haven't tried it, but -fno-new-ttp-matching was deleted.
If this is still a problem, reopen the issue.
Though to be fair, citra doesn't build for me right at the moment anyway.
